/**
 * Transforms JavaScript code generated by Blockly into MicroPython code for ESP32
 */
export function generateMicroPythonCode(jsCode: string): string {
  // MicroPython code header with required libraries and pin definitions
  const micropythonHeader = `# SmartCar Creator Generated Code
# Target: ESP32 with MicroPython

from machine import Pin, PWM, time_pulse_us
import time

# --- Helper Classes ---
# A simple NewPing library implementation for MicroPython
class NewPing:
    def __init__(self, trigger_pin, echo_pin, max_distance=200):
        self.trigger_pin_num = trigger_pin
        self.echo_pin_num = echo_pin
        self.max_distance = max_distance
        self.trigger = Pin(trigger_pin, Pin.OUT)
        self.echo = Pin(echo_pin, Pin.IN)

    def ping_cm(self):
        self.trigger.low()
        time.sleep_us(2)
        self.trigger.high()
        time.sleep_us(10)
        self.trigger.low()
        
        # Using machine.time_pulse_us for better accuracy
        # Set timeout to max_distance * 2 * 29.1 (round trip time in us for max distance)
        timeout = self.max_distance * 2 * 29.1
        duration = time_pulse_us(self.echo, 1, int(timeout))
        
        if duration < 0:
            return 0 # Timeout
            
        # Speed of sound is approx 343m/s or 29.1 us/cm
        # Distance = (duration / 2) / 29.1
        distance = (duration / 2) / 29.1
        
        if distance > self.max_distance:
            return 0 # Out of range
            
        return int(distance)

# --- Pin Definitions ---
# Note: Adjust these pins based on your ESP32 wiring
TRIGGER_PIN = 15
ECHO_PIN = 14
LEFT_MOTOR_PIN1 = 26
LEFT_MOTOR_PIN2 = 25
RIGHT_MOTOR_PIN1 = 33
RIGHT_MOTOR_PIN2 = 32
LEFT_MOTOR_ENABLE_PIN = 13
RIGHT_MOTOR_ENABLE_PIN = 12

# --- Constants ---
MAX_DISTANCE = 300 # Maximum distance for ultrasonic sensor (in cm)

# --- Hardware Initialization ---
# Initialize motors
left_motor_pin1 = Pin(LEFT_MOTOR_PIN1, Pin.OUT)
left_motor_pin2 = Pin(LEFT_MOTOR_PIN2, Pin.OUT)
right_motor_pin1 = Pin(RIGHT_MOTOR_PIN1, Pin.OUT)
right_motor_pin2 = Pin(RIGHT_MOTOR_PIN2, Pin.OUT)

# Initialize PWM for motor speed control
left_motor_enable = PWM(Pin(LEFT_MOTOR_ENABLE_PIN))
right_motor_enable = PWM(Pin(RIGHT_MOTOR_ENABLE_PIN))
left_motor_enable.freq(1000)
right_motor_enable.freq(1000)

# Initialize sensors
sonar = NewPing(TRIGGER_PIN, ECHO_PIN, max_distance=MAX_DISTANCE)

# --- Function Implementations ---
def moveForward():
    speed = 800  # PWM duty cycle (0-1023 for ESP32)
    left_motor_pin1.high()
    left_motor_pin2.low()
    right_motor_pin1.high()
    right_motor_pin2.low()
    left_motor_enable.duty(speed)
    right_motor_enable.duty(speed)
    print("Moving forward")

def moveBackward():
    speed = 800
    left_motor_pin1.low()
    left_motor_pin2.high()
    right_motor_pin1.low()
    right_motor_pin2.high()
    left_motor_enable.duty(speed)
    right_motor_enable.duty(speed)
    print("Moving backward")

def turnLeft():
    speed = 700
    left_motor_pin1.low()
    left_motor_pin2.high()
    right_motor_pin1.high()
    right_motor_pin2.low()
    left_motor_enable.duty(speed)
    right_motor_enable.duty(speed)
    print("Turning left")
    time.sleep(0.5)
    stopMovement()

def turnRight():
    speed = 700
    left_motor_pin1.high()
    left_motor_pin2.low()
    right_motor_pin1.low()
    right_motor_pin2.high()
    left_motor_enable.duty(speed)
    right_motor_enable.duty(speed)
    print("Turning right")
    time.sleep(0.5)
    stopMovement()

def stopMovement():
    left_motor_pin1.low()
    left_motor_pin2.low()
    right_motor_pin1.low()
    right_motor_pin2.low()
    left_motor_enable.duty(0)
    right_motor_enable.duty(0)
    print("Motors stopped")

def wait(seconds):
    print(f"Waiting for {seconds} seconds")
    time.sleep(float(seconds))

def readUltrasonicSensor():
    time.sleep_ms(50)
    distance = sonar.ping_cm()
    print(f"Distance: {distance} cm")
    return distance if distance > 0 else MAX_DISTANCE

# --- Main Program Logic ---
# This is where the code from the blocks will be inserted.
def main():
`;

  // MicroPython code footer
  const micropythonFooter = `
# --- Main program loop ---
# Run the main program
if __name__ == "__main__":
    stopMovement() # Ensure motors are stopped at the beginning
    time.sleep(2)  # Wait for 2 seconds before starting
    while True:
        main()
        time.sleep_ms(50) # Small delay at the end of each loop
`;

  // Process the JavaScript code
  // Replace JS function calls with Python function calls
  // Indent each line for the main function
  const processedJsCode = jsCode
    .replace(/;\s*$/gm, '') // Remove trailing semicolons
    .split('\n')
    .filter(line => line.trim() !== '') // Remove empty lines
    .map(line => '    ' + line.trim()) // Indent each line
    .join('\n');

  // Combine all parts to create the final MicroPython code
  return micropythonHeader + processedJsCode + micropythonFooter;
}
